### ISSUE TITLE
Node throws syntax error when used in angular universal app

### ISSUE THREAD

**Issue by bkielczewski** [eligrey/FileSaver.js#496]
Node 10.x. 

1.3.8 is fine, but since 2.0.0 it is as below:

```
__WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));else {}})(this,function(){"use strict";function b(a,b){return"undefined"==typeof b?b={autoBom:!1}:"object"!=typeof b&&(console.warn("Depricated: Expected third argument to be a object"),b={autoBom:!b}),b.autoBom&&/^\s*(?:text\/\S*|application\/xml|\S*\/\S*\+xml)\s*;.*charset\s*=\s*utf-8/i.test(a.type)?new Blob(["\uFEFF",a],{type:a.type}):a}function c(b,c,d){var e=new XMLHttpRequest;e.open("GET",b),e.responseType="blob",e.onload=function(){a(e.response,c,d)},e.onerror=function(){console.error("could not download file")},e.send()}function d(a){var b=new XMLHttpRequest;return b.open("HEAD",a,!1),b.send(),200<=b.status&&299>=b.status}function e(a){try{a.dispatchEvent(new MouseEvent("click"))}catch(c){var b=undefined.createEvent("MouseEvents");b.initMouseEvent("click",!0,!0,undefined,0,0,0,80,20,!1,!1,!1,!1,0,null),a.dispatchEvent(b)}}var f= false?undefined:"object"==typeof self&&self.s

SyntaxError: Invalid destructuring assignment target
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

**Comment by Ruffio** [comment]
Are we sure that this has something to do with FileSaver? FileSaver is not mentioned, but Bootstrap is...

**Comment by bkielczewski** [comment]
Yeah, like literally the code from FileSaver.js is printed with the stack trace.

Bootstrap you're referring to at the bottom is part of nodejs bootstrapping process, that's why it's the first call in the stack trace. Comes from https://github.com/nodejs/node/blob/master/lib/internal/bootstrap/node.js
